name: Code Test

on: [ push, pull_request ]

jobs:
  test:
    name: Run unit test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - 'pypy3'
        java-version:
          - '8'
        plantuml-version:
          - '1.2020.19'
        assistant-plantuml-version:
          - '1.2020.16'
          - '1.2019.13'
          - '1.2018.14'
          - '1.2017.20'

    services:
      plantuml:
        image: plantuml/plantuml-server
        ports:
          - 8080:18080

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Checkout demo code
        uses: actions/checkout@v2
        with:
          repository: HansBug/plantumlcli-testfile
          path: demo
          fetch-depth: 20
      - name: Set up system dependences on linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make
          sudo apt-get install -y graphviz
          sudo dot -c
          sudo apt-get install -y libxml2-dev libxslt-dev python-dev  # need by pypy3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: Test the basic environment
        run: |
          python -V
          pip --version  
          pip list
          java -version
          javac -version
          tree .
          cloc plantuml
          cloc test
      - name: Test the plantuml in use (${{ matrix.plantuml-version }} and ${{ matrix.assistant-plantuml-version }})
        env:
          TEST_PLANTUML_HOST: http://localhost:18080
        run: |
          java -jar demo/jar/plantuml.${{ matrix.plantuml-version }}.jar -version
          java -jar demo/jar/plantuml.${{ matrix.assistant-plantuml-version }}.jar -version
          curl -L "${TEST_PLANTUML_HOST}/txt/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IG80"
      - name: Run unit test and benchmark
        env:
          PRIMARY_JAR_VERSION: ${{ matrix.plantuml-version }}
          ASSISTANT_JAR_VERSION: ${{ matrix.assistant-plantuml-version }}
          TEST_PLANTUML_HOST: http://localhost:18080
        run: |
          source env.sh
          pytest ./test --cov-report term-missing --cov=./plantumlcli -sv -m unittest --durations=10
          pytest ./test -sv -m benchmark --durations=0
      - name: Upload coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ format('{0}-{1}-{2}-{3}', runner.os, matrix.python-version, matrix.java-version, matrix.assistant-plantuml-version) }}
          COVERALLS_PARALLEL: true
        run: |
          pip3 install --upgrade coveralls
          coveralls

  coveralls:
    name: Finish coveralls
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish